[versions]
jetbrainsKotlinPluginVersion = "1.9.21"
androidApplicationPluginVersion = "8.4.2"
coreKtx = "1.13.1"
material = "1.12.0"
appcompat = "1.7.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
junitVersion = "1.2.1"
junit = "4.13.2"
espressoCore = "3.6.1"

gsonLibraryVersion = "2.11.0"

koinAndroid = "3.3.0"
koinCore = "3.2.2"
koinTest = "3.1.2"

hiltAndroidPluginVersion = "2.51.1"
hiltAndroidLibraryVersion = "2.51.1"

googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "21.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

gson = { module = "com.google.code.gson:gson", version.ref = "gsonLibraryVersion" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidLibraryVersion" }

firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlinPluginVersion" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidPluginVersion" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
